language: groovy

jdk:
- oraclejdk7

after_success:
- ./gradlew jacocoTestReport coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa61cd42119154cf9252
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
