package org.ajbrown.gradle.plugins.raml

import org.gradle.api.Project

/**
 * Configuration of the RAML documentation publisher and validator.
 * @author A.J. Brown <aj@ajbrown.org>
 */
class RamlExtension {

    /**
     * The location of the RAML specification.  This can be either a file path or a URL.
     */
    String source

    /**
     * The location to output the HTML files generated by this plugin.
     */
    String htmlDestination

    Project project

    RamlExtension( Project project ) {
        this.project = project
    }

}
